- .github/workflows/auto-author-assign.yml
Action that automatically assigns author to pr when its opened or reopened. 
If we want to, we could do the same for issues by adding the following lines:
```
on:
issues:
types: [ opened, reopened ]
pull_request_target:
types: [ opened, reopened ]
permissions:
issues: write
pull-requests: write
```
Action copied from: https://github.com/marketplace/actions/auto-author-assign
Note: I did edit L17 from `repo-token: ${{ secrets.YOUR_TOKEN }}` to `repo-token: ${{ secrets.GITHUB_TOKEN }}` (based on the action from the [AdvancedR course](https://r-cubed-advanced.rostools.org/sessions/build-website#automate-rendering-the-website) since VS Code gave me a warning about YOUR_TOKEN)
> feat: add auto author assign action

- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
- .github/ISSUE_TEMPLATE/USER-STORY.yml
- Fix link to Code of Conduct in issue templates 
- Capitalise 's' in user story to fit the other issue templates
- Put quotation around options in dropdown (hoping it will fix layout issues - options were shown in curly brackets, see below)
> feat: 13 bug incorrect link to code of conduct in issue templates all three

- .github/PULL_REQUEST_TEMPLATE/pull-request-code.md
- .github/PULL_REQUEST_TEMPLATE/pull-request-documentation.md
we will not implement pre-commit hooks after all
> fix: remove pre-commit hooks from checklist

- .vscode/extensions.json
- common/justfile/docker-dev
+ [X] Add Ruff to extensions.json for VS Code users
+ [X] Add Ruff to justfile - @lwjohnst86 I have added lint-python and format-python in the docker-dev justfile. Is that the correct location?
Closes seedcase-project/seedcase-sprout#31 when they have been synced to the other repos
Do we want a GitHub action as well?
> feat: add ruff

- .vscode/json.code-snippets
These changes are done for mostly aesthetic reasons.
> fix: :art: Mostly stylistic, having spaces around TODO, plus add `:`

- .github/sync.yml
These changes are done because I created the community repo and it needs to be connected.
> ci: :construction_worker: Add community repo to be sync'ed with standard files

- common/justfile/web
These changes are done because this makes it easier for others to re-build websites using the latest version of Quarto. So rather than depend on the developer installing Quarto, you can render the website as long as you have Docker :grin:
> build: :hammer: Use docker command in justfile for rendering websites with Quarto

- common/justfile/django
- This PR fixes the build `justfile` for starting and stopping the Docker image. Mostly to simplify them, as well as remove the "build" one (don't think we need it).
> fix: :hammer: Fix docker build recipes in justfile.

- .vscode/extensions.json
- .vscode/settings.json
- This PR adds the feature of using the conventional branch VSCode extension to the recommended extensions, as well as some settings on the names to give for the branches.
> feat: :wrench: Add conventional branch and its settings

- .vscode/settings.json
- This PR fixes the issue with the `settings.json` file not recognizing `#` as the start of comments. 
- Also added a "chore" type for the conventional branch.
No review is necessary, was already done in the sprout repo.
> chore: :wrench: Use correct comment character (can't use `#`) and add `chore` as a type

- .github/sync.yml
- This PR fixes the typo in the sync'ing file. It should have been "json" not "quarto" after we dealt with that previous bug.
> ci: :pencil2: This should have been "json" not "quarto" after the renaming

- common/ruff.toml
- This PR removes the max line length of 79, so we return to the ruff and black default of 88.
- These changes are done after talking to @philter87 and @lwjohnst86 about this.
> fix: :art: remove max line length of 79 so we return to default of 88

- common/ruff.toml
This includes all init files in the repo. 
- This PR adds that Ruff ignores the F401 ("module imported but unused”) error in all `__init__.py` files in the repo. 
- Currently, we add unused imports in the init files to ease the import in other modules (@philter87 correct me, if I'm wrong), and add a `#noqa` comment after each import to get Ruff to ignore these specific lines. This PR fixes this globally, for all init files,  instead.
Current fix to get Ruff to ignore this, using the `#noqa` comment:
** Example of how including these unused modules in the `__init__.py` files simplifies imports:
Importing "data_import" and "file_upload" in the init module in `views.__init__.py` like this ...
... Enables a simple looking import of them in `urls.py` like this:
**Alternative solution** …
> feat: ignore "module imported but unused" error in init files

- .vscode/extensions.json
- This PR adds SQLite3 Editor to the list of recommended VS Code extensions. 
- As discussed at the demo 15 February, this is a nice extension for examining the database as well as edit the data within it (in contrast to the SQLite Viewer extension, which is readonly).
> build: add sqlite3-editor to recommended extensions

- .github/workflows/test.yml
After I removed migrations from git, we need to run makemigrations everytime
See also Issues #217
> makemigrations are added

- .gitignore
@philter87 had added this to the [PR#213: Goodbye migrations](https://github.com/seedcase-project/seedcase-sprout/pull/213), but these were overwritten in a sync. 
So, I have added it here again (I have just shortened the original comment)
EDIT: Philter has added `persistant_storage` as well.
> misc: ignore migrations and persistant storage

- common/ruff.toml
- This PR adds that Ruff ignores D100, i.e., "missing docstring in public modules"
- These changes are done since the docstrings at the top of files (as we currently write them at least) don't really add new information. Therefore, they are kind of redundant.
> build: ignore d100

- .vscode/settings.json
To avoid having to fix organising import sorting by hand, I have added that it will happen on save 👍
I have made some simple (informal) tests locally and it seems to work as expected.
> fix: add organise code imports on save

- common/justfile/django
In this PR, I attempt to add a `just` recipe to that resets Sprout locally. This includes removing `__pycache__` folders, removing the db `db.sqlite3`, and all migrations. 
Im not too familiar with the commands I have used to achieve this, but the local testing of these seemed to work as expected.
> feat: add reset-local recipe

- .vscode/settings.json
- This PR makes the default saving so a file ends with a newline. Git tends to like that better and won't show a warning symbol in PRs.
> style: :wrench: default to save a final newline, since Git likes that better

- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
- .github/ISSUE_TEMPLATE/USER-STORY.yml
- This PR removes the checkbox for people to click when they create an issue to a markdown/statement saying they are following our code of conduct. 
- These changes are done because of the checkbox looks like a "completed" item in the issue
> fix: :zap: change code of conduct checkbox to statement

- .vscode/settings.json
- This PR adds the UK dictionary to CSpell in the main settings on .github.
- These changes are done because the Seedcase team have decided that we are happy with both UK and US spelling in our code and documentation.
Closes #35 
I'm not sure how I would go about testing this, other than checking that it accepts both UK and US spelling, which it does.
For all PRs that are not general documentation
> feat: update settings to enable UK dictionary in CSpell

- .github/sync.yml
Signe added the debugger for Django, and we forgot to connect the `launch.json` file to be sync'ed.
> ci: :construction_worker: forgot to add launch.json to sync'ing between repos

- .github/CODEOWNERS
Now that we have the dependabot working in Sprout, we don't want everyone to be requested for review whenever a new version is bumped and a PR is created.
> chore: :technologist: remove `pyproject.toml` and `poetry.lock` from triggering reviewers

- common/justfile/django
The justfile recipe for building a website in a non-root location needs to move to that folder to find the `_extensions/` theme.
> build: :hammer: needs to temporarily switch to docs folder to build website

- .vscode/settings.json
These changes are done to the VSCode settings, because it needs a path and I put the poetry command.
> chore: :hammer: fix path to pytest to link to local poetry venv

- .github/sync.yml
I forgot to move this down to the website section. The PR template in `.github` shouldn't synching to all repos, only to the website repos.
> ci: :construction_worker: move synching of website PR template to only website repos

- .github/workflows/puml-to-svg.yml
It is very annoying to have to update the svg files. So this adds a reusable workflow to solve that problem.
Closes #179
This PR needs a quick review. Focus on the Git message used when this runs.
> ci: :construction_worker: add reusable workflow to generate SVG from puml files

- .github/workflows/deploy-docs-with-python.yml
This PR will (I hope) fix the website build error happening because Quarto can't find the Poetry venv.
Closes seedcase-project/template-python-project#14
No review necessary.
> ci: :construction_worker: setup Python venv so Quarto finds it correctly

- .github/workflows/test.yml
This PR removes django related steps from our test workflow, since: 
1) we don't develop in Django currently
2) it started failing in seedcase-project/seedcase-sprout#844 after I renamed the `sprout` folder
Related to seedcase-project/seedcase-sprout#845
> ci: :fire: remove django related steps

- .github/workflows/test.yml
This PR removes "django" from the name of the workflow, since we don't use Django anymore.
> docs: :pen: remove django from test workflow name

- .github/workflows/test.yml
The failing tests after removing Django are also caused by using `--no-root`. This option was used becuase the Django project didn't like it, but a Python package project needs it.
This PR doesn't need a review.
> ci: :construction_worker: needs to install the package itself too

- .github/workflows/reusable-build-docs-with-python.yml
Quarto has to be in the activated venv in order for things to build (I think).
> ci: :bug: Quarto needs to find/be in the venv

- .editorconfig
- .github/workflows/reusable-update-python-project-version.yml
Finally figured out how to do this. I set up a GitHub App that will be able to use a specific token to only push changes to main for updating versions, rather than my current setup that uses a similar token but that lasts longer. This token only is used in the workflow then gets deleted. So improves security.
Closes #196
Doesn't need a review. but happy to explain it more.
> ci: :lock: add GitHub App that makes short-lived tokens

- .github/workflows/reusable-build-python.yml
This PR adds the `just check-unused` recipe to the reusable build workflow. 
As noted here: https://github.com/seedcase-project/seedcase-sprout/pull/1330#pullrequestreview-2839471750
This PR needs a quick/an in-depth review.
> ci: :technologist: add `just check-unused` to resuable build workflow

- .github/workflows/reusable-build-python.yml
The uv setup action has been improved a lot. These `with:` options aren't needed anymore.
> ci: :construction_worker: uv GitHub action's defaults mean these aren't needed anymore

- .github/workflows/reusable-add-to-project.yml
Not sure what happened, but `gh pr edit` now errors (sometimes randomly it doesn't). So this forces it to edit the specific repository.
No review is needed.
> ci: :bug: new bug claiming not to find repo, so being explicit here

- .github/workflows/reusable-release-package.yml
Adds `pypi` as the default `environment` as passes the `environment` to the release job.
This PR needs no review. I'll merge it in to see if this fixes the issue of not being able to publish to `pypi` at the moment 🤞
> ci: :green_heart: set default `environment` as `pypi` in release workflow

- .github/workflows/reusable-release-package.yml
Fix the name of the job, it only releases to GitHub.
> ci: :memo: workflow only releases to GitHub, not PyPI

- .github/workflows/reusable-build-docs.yml
The `netlify-token` can't be required if using `hosting-provider: 'gh-pages'`
No review is needed.
> fix: :bug: netlify token can't be required anymore

- .github/workflows/reusable-build-docs-with-python.yml
- .github/workflows/reusable-build-docs.yml
- .github/workflows/reusable-release-project.yml
Workflows like releasing and building the website should stop if another, newer workflow is started. This prevents errors from running e.g. several release workflows in a row (which may make the same tag). Building the website should use the latest commit and cancel previous ones.
I don't actually know if this will work, or if it needs to be in the calling workflow (not here).
Closes #275, closes #302
Needs a quick review.
> feat: :construction_worker: `concurrency` to cancel previous running workflows

- .github/workflows/reusable-build-docs-with-python.yml
This partly fixes that we don't need to require GITHUB_TOKEN, but also adds the ability to deploy to gh-pages.
> feat: :construction_worker: allow build Python docs to deploy to gh-pages
