- .vscode/quarto.code-snippets
I have a few times wanted to add a video (to the Git guidelines) and have forgotten how to do it every time. So now, I have added a code snippet for it :)
> feat: :sparkles: add insert video code snippet

- .vscode/quarto.code-snippets
I have used paneltabs quite a lot for the Git guidelines, but can never remember how to add them. So, now I have added it here :-)
> feat: :sparkles: add panel tab code snippet

- .github/sync.yml
Connect the newly created decisions repo to be sync'ed the the config and settings files.
> ci: :construction_worker: Connect decisions repo to be sync'ed

- .github/sync.yml
- This PR adds the `data` repo to the sync file, so that common settings and config files get sync'ed
> ci: :construction_worker: Add data repo to sync for config and setting files

- .github/pull_request_template.md
type of review (light or in-depth) added as options under Reviewer Focus
> feat: update PR template with type of review

- common/justfile/django
- This PR 
adds the development justfile recipes, taken from Sprout repo.
- Adds the recipe to generate a single puml file, run Django tests, install Python dependencies, and run a fuller set of checks on Python code with Ruff.
This PR doesn't need a review.
> feat: :hammer: Add justfile recipe that installs necessary python dependencies

- .github/sync.yml
- This PR fixes an issue where the PR template only works in VSCode GitHub extension if the file is in the actual repo. So synching the file to each repo so VSCode finds it.
> ci: :technologist: VScode doesn't find community health files, so saving this template in each repo

- common/justfile/django
- This PR adds the justfile recipes from the Sprout repo, as well as adds dependency recipes (e.g. to install something before running the recipe).
- The dependency changes are done because otherwise we need to manually run multiple recipes in order to run one (e.g. first install, then migrations, etc.).
This PR does not need a review.
> build: :hammer: Move over justfile recipes from sprout

- .github/sync.yml
- This PR adds the mustache file to be synched with the other repos.
> ci: :construction_worker: Add google docstrings mustache file to synching

- .github/workflows/test.yml
- This PR upgrades the `setup-python` version to the latest (v5). The older version used a deprecated Node.js 16.
> ci: :arrow_up: the setup python action version was bumped to `v5`

- .vscode/extensions.json
- This PR adds an extension that makes it easier to work with Django HTML template files. For instance, it formats them, gives help, etc.
> chore: :technologist: Add VSCode extension to help working with HTML template files

- common/justfile/django
Fixing typo "packagee" to "package"
> fix(typo): packagee -> package

- .vscode/settings.json
There are some things I feel VS Code isn't doing for me, which I think is more to do with learning which extension to install and use. Pylance seems to be a better tool for coding in Python and getting reliable help/support (e.g. imports showing an error at not finding a package that is installed via Poetry).
> chore: 🧑‍💻 include pylance for better Python coding in VS Code

- .vscode/settings.json
Update this from the Sprout repo
> chore: :technologist: set default Python to the project's `.venv` folder location

- common/justfile/django
- This PR updates the justfile to load all JSON files found in fixture folders, rather than one by one (if there are more). This also makes the justfile more generic for other projects too.
> build: :white_check_mark: load all fixtures, before running tests

- .vscode/extensions.json
- .vscode/settings.json
- common/justfile/django
- This PR adds a Django specific HTML linter since the other one didn't seem to handle some shortcodes well.
> chore: :technologist: small development improvements

- common/justfile/django
- This PR adds the removal of `.csv` files in the folder `persistent-storage/raw` 
- To avoid the local folder of raw files explode (as mine did with > 300 files), we might as well add it to the `reset-local` recipe
> feat: add removal of persistent storage raw files to `reset-local` recipe

- .vscode/launch.json
- This PR adds the `.vscode/launch.json` file with a debugger called "seedcase-debugger". This allows us to set break points and assess variables and views at these break points using the built in"Run and Debug" feature in VS Code. 
- To use the debugger: 
- Find "Run and Debug" in the side menu in VS Code
- Check that it says "seedcase-debugger" in the top, next to the "Play" icon button (don't click it yet)
- Set break points where you want the code to stop by going to the script you want, and click at the left side of the line (a red dot will appear) 
- Then, in the "Run and debug" tab, click "Play". The debug console will open. Follow the local host link (as when running `just start-app`) and go to the page you want to debug. The code will stop at your break point(s) and you can …
> feat: :zap: set up "seedcase-debugger"

- .github/ISSUE_TEMPLATE/DISCUSSION-POST.yml
- .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
- This PR adds the feature to create an issue template for discussion posts.
- These changes are done because it would be good to be more consistent in setting up discussion posts.
Closes #40 
This is one of those where we need to merge in order to check that it works.
For general documentation:
> feat: create new issue template for discussions

- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- This PR removes the email field, since we can ask for details in the issue and, therefore, don't need an email.
Closes #54
> fix: :fire: remove email field in bug report

- .vscode/settings.json
- This PR enables CSpell in Quarto (`.qmd`) files
- These changes are done since we mainly write documentation ind Quarto files
> feat: enable cspell in quarto files

- .github/sync.yml
> ci: :truck: update link to renamed `seedcase-website` repo

- common/justfile/django
- common/justfile/web
- This PR changes the output of the just commands related to generating outputs from the `.puml`s. It's changed from `.png` to `.svg`. 
- I tested the changes in another repo and it seems to work as expected 👍 
Closes #132
> feat: :sparkles: change just puml command output to svg

- .github/workflows/add-to-project.yml
I haven't tested this, need to merge it in and see how it runs.
> ci: :technologist: workflows to add issues and PRs to project board

- .github/workflows/add-to-project-action.yml
- .github/workflows/add-to-project.yml
Can't use permissions within the reusable workflow
> ci: :bug: the workflow can't have permissions in the reusable part

- .github/workflows/add-to-project-action.yml
- .github/workflows/add-to-project.yml
> ci: 🐛 need quotes around the workflow variables

- .github/dependabot.yml
So I get assigned to the PRs and it makes it easier for me to see it.
Is a very small change and only needs a very quick review.
Closes #134
> ci: :construction_worker: assign me to dependabot PRs

- .github/workflows/sync-files.yml
For instance, by using conventional commit and branch style, using a fine-grained GitHub token to improve security, etc.
Only needs a quick review.
Closes #160, closes #159
> ci: :construction_worker: revise file sync to match our workflow better

- .github/workflows/test.yml
Use pytest in GitHub workflow.
> ci: :construction_worker: switch to using pytest for workflow rather than unittest

- .vscode/settings.json
- common/justfile/django
These changes update what I added to the PR for adding pytest to Sprout, so that they are found here as well.
> build: :hammer: update synch'ing development files from changes made in Sprout

- .vscode/launch.json
This was added by Marton earlier, we just forgot to move it over to here so it synchs up.
> chore: :technologist: add launcher for debugging a file with VSCode

- .github/workflows/test.yml
These changes upgrade the Python version used in the CI.
> ci: :construction_worker: upgrade Python version

- .vscode/extensions.json
> chore: :wastebasket: remove markdownlint from recommendations

- .github/pull_request_template.md
These changes follow the changes in seedcase-project/template-python-project#10
Closes #
This PR needs a quick/in-depth review. **--this will still be there--**
Focus on CHANGES. **--this will be removed--**
> chore: :technologist: remove reviewer focus section

- .github/workflows/deploy-docs-with-python.yml
This adds a workflow that runs the Python code in the docs and stores the output in the HTML website, so we can be able to check that the code in the docs is correct to what we are building :grin:
> ci: :construction_worker: workflow to build docs that include Python code

- .github/workflows/deploy-docs-with-python.yml
> ci: :pencil2: typo in sourcing, it isn't a folder

- .github/workflows/deploy-docs-with-python.yml
Maybe this will fix the build...
> ci: :construction_worker: install poetry deps directly into container env so Quarto finds it

- .github/workflows/deploy-docs-with-python.yml
Another attempt at fixing this CI.
> ci: :construction_worker: install via pip and output a requirements file to build websites

- .github/workflows/reusable-update-python-project-version.yml
I made a typo... Ooops!
This PR doesn't need a review.
> ci: :pencil2: fix typo in secret name

- .github/workflows/reusable-update-python-project-version.yml
This PR updates the version workflow to also update the changelog. I hope this works as I expect it to, since these updates don't feel very controversial 🤞 
Closes #199 
This PR needs an in-depth review.
> ci: :construction_worker: update version workflow to update changelog

- .github/workflows/reusable-build-docs-with-python.yml
After changing to `src/` need to formally install the package.
Doesn't need a review.
> ci: :bug: need to install the local package

- .github/workflows/add-to-project.yml
- .github/workflows/reusable-add-to-project.yml
Converts the "add to board" workflow to be reusable.
Closes #193
> ci: :construction_worker: convert "add to board" to a reusable workflow

- .github/workflows/reusable-build-docs-with-python.yml
The command should be `uv run`, not `uv python -m`.
> ci: :bug: should be `uv run`

- .github/workflows/reusable-build-docs-with-python.yml
Hopefully this fixes the build issue.
> ci: :bug: set Python location so Quarto can find it

- .github/workflows/reusable-build-python.yml
> ci: :construction_worker: need to use sudo to install justfile

- .github/workflows/reusable-build-python.yml
Forgot to fix these doc items.
Doesn't need a review.
> ci: :memo: rename to be simply "build"

- .github/workflows/reusable-build-docs-with-python.yml
- .github/workflows/reusable-build-docs.yml
Updating these workflows to match what has been done in the other repos.
Doesn't need a review.
> ci: :construction_worker: add spell checking to doc workflows

- .github/workflows/reusable-build-python.yml
> ci: :construction_worker: add spell checker to Python package build

- .github/workflows/reusable-build-python.yml
- .github/workflows/reusable-update-python-project-version.yml
I added something to a workflow that isn't needed. Not sure why I did.
Also increased the version number of uv action.
> chore: :twisted_rightwards_arrows: clean up workflows

- .github/workflows/reusable-sync-files.yml
Since it's used in three different repos, good to make it reusable.
Closes #229
> ci: :construction_worker: add reusable sync files workflow

- .github/workflows/reusable-release-package.yml
Indenting was slightly off. Fixed.
> ci: :art: fix formatting issue with workflow

- .vscode/extensions.json
- .vscode/settings.json
Simple change, just removes the comments and adds two extra branch types.
> chore: :wrench: tidy up the `vscode` settings
